### ISSUE TITLE
Issue with github npm installs

### ISSUE THREAD

**Issue by louy** [kolodny/wavy#1]
This module breaks npm install for modules from github for some reason. I get messages like this:

> npm WARN skippingAction Module is inside a symlinked module: not running add modulename@version node_modules/modulename

The solution was to add a `preinstall` script that contains `rm -rf node_modules/~`.

**Comment by kolodny** [comment]
I can't seem to replicate, can you provide a script that would show the issue. It should look like this:

```bash
cd $(mktemp -d -t tmp) # go to a newly created tmp directory
echo '{}' > package.json
npm install --save lodash
# ... do more stuff here until something breaks
```
