### ISSUE TITLE
Bug: breaks when a dependency uses wavy

### ISSUE THREAD

**Issue by keenahn** [kolodny/wavy#15]
Package A requires wavy
Package B requires Package A
Package A breaks because the `~` points to Package B in the flat `node_modules` directory

Tested with npm and yarn

**Comment by keenahn** [comment]
For anyone else who lands here, I have refactored all my code to use https://www.npmjs.com/package/app-module-path

**Comment by kolodny** [comment]
Yeah, sorry about the slow response, this package has some serious limitations esp with the flattened by default npm mechanism. This package only really works on the top level of an app. Put another way, there shouldn't be any published modules that use this, and this module shouldn't be a transitive dependency. I've tried unsuccessfully to iron that issue out but had no real success. If you have any ideas about how to fix that feel free to open a PR
