### ISSUE TITLE
Can't symlink on windows

### ISSUE THREAD

**Issue by oToToT** [kolodny/wavy#17]
Can't symlink on windows if the disk format is exFAT.
Are there any other way to use it?

**Comment by tamusjroyce** [comment]
Yes. There are many other ways to use this... Such as obviously converting your disk to ntfs. This is possible, even for flash drives. But below I am making the assumption that cannot be done for some reason in your case.

1. Buy a USB drive and format it as ntfs (or possibly udf...not sure if that works, but it supports symlinks)? Copy the project and use this tool from there?

2. It also seems like 7zip (I believe?) and tar archive formats both support symlinks. You can archive your project from a ntfs/ext4/brtfs/etc drive in a way that preserves symlinks. Copy it to the exFAT drive.  Then on another computer that drive is moved to, when you unarchive it back to a ntfs/ext4/brtfs/etc drive, that symlink will remain intact.

daemontools has malware (or has in the past...at very least, it is not open source). There are tools that will mount a file as a disk image. And that image may be formatted as ntfs. Even if it is stored on a exFAT partition. It may require a paid tool.

I am highly against changing this projects code to work on filesystems that do not support symlinks. It would not be worth the work.

If the above is helpful, please close this. : )
