### ISSUE TITLE
Name idea

### ISSUE THREAD

**Issue by matejkramny** [kolodny/wavy#3]
Call it bacon! :)

**Comment by kolodny** [comment]
Whats wrong with wavy? :disappointed: 

I really wanted https://www.npmjs.com/package/tilde

**Comment by matejkramny** [comment]
I am not implying something is wrong with the name.. This was merely an idea when I saw this package and what it does.

There was a joke some time ago about this (invalid) syntax:

```
var ~ = require('bacon');
```

Similar to `_` (lodash, underscore) and `$` (jquery).

**Comment by kolodny** [comment]
hmm, still not sure what the point of this issue is. Is this action-able?

**Comment by matejkramny** [comment]
There is no point

I had an idea which you considered wasn't good. It doesn't matter actually
