### ISSUE TITLE
Change base directory.

### ISSUE THREAD

**Issue by DylanPiercey** [kolodny/wavy#7]
Is it possible to allow for some configuration to change the project root? Currently it's directly above `node_modules` however in most of my projects all of the js is stored in `/js`, `lib`, `src` or similar.

I think it would be nice to simply add a package json option to set the `wavy` root path.

**Comment by kolodny** [comment]
I'd consider that a little too heavy for this tool, since it would require more cognitive load to know to look in package.json to know what `require('~/foo')` actually does
