### ISSUE TITLE
Symlink under windows

### ISSUE THREAD

**Issue by Nicholaiii** [kolodny/wavy#9]
Node needs to be run as admin for symlinks to work. 

``````
$ pnpm install wavy --save
wavy ERROR ? 
 ! EPERM: operation not permitted, symlink 'd:\Projects\BAS\qMan\node_modules\.tmp\fb8070d0-3970-45be-8496-6a75a34b3978' -> 'd:\Projects\BAS\qMan\node_modules\.store\wavy@1.0.2'```
``````

**Comment by kolodny** [comment]
I don't know much about pnpm, you can still use `npm install wavy`

**Comment by phra** [comment]
so.. is it working on windows or not? i don't have a win machine to try at the moment. if there are no problem with it, we should close this ticket.

**Comment by kolodny** [comment]
This works with npm on windows

**Comment by tamusjroyce** [comment]
I noticed when you install [git](https://git-scm.com/downloads), it gives you an option to support symlinks. It requires admin rights to apply its changes. As it alters windows registry. But after that, admin rights are no longer required.

This registry change might be worth looking into. And it could be why some Windows users do not require admin rights.

If this is incorrect, let me know. I will remove the comment. Or you might close the ticket if there is no issue. : )

**Comment by kolodny** [comment]
This library uses juntions which based on my limited testing works on windows. 🤷‍♂️

**Comment by fluvf** [comment]
Windows has had support for symlinks since Vista+, but only recently users are allowed to make them without special / elevated permissions. But junctions work fine, as long as you've got permissions for the folders. This works fine with _recent_ versions of both `npm` and `pnpm`. I haven't tested older versions

**Comment by kolodny** [comment]
Closing this since there isn't anything actionable to do on this. Feel free to reopen if you feel that to be incorrect
